[build]
  command = "npm run build"
  publish = "dist"

# SPA redirect rule for all frontend routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect for admin login API requests to your backend on Render
[[redirects]]
  from = "/adminlogin/*"
  to = "https://salessyncpython.onrender.com/adminlogin/:splat"
  status = 200
  force = true

# Redirect for general API requests to your backend on Render
[[redirects]]
  from = "/api/*"
  to = "https://salessyncpython.onrender.com/api/:splat"
  status = 200
  force = true
