[build]
  command = "npm run build"  # your build command
  publish = "dist"  # your publish directory

[[headers]]
# Define which paths this header config applies to
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY" #Example Security Header

[[redirects]]
   from = "/api/*"
   to = "https://salessyncpython.onrender.com/api/:splat"
   status = 200
   force = true